spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/api-docs/**, /api/v1/auth/**,  /api/v1/jwt/parse, /api-docs/auth
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**, /api-docs/user
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/book/**, /api-docs/book
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/v1/review/**, /api-docs/review
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:50005/eureka/